/* Home page */
export const CHANGE_COURSE_SEARCH = "CHANGE_COURSE_SEARCH";

/* University search box related */
export const CHANGE_UNIVERSITY_SEARCH = "CHANGE_UNIVERSITY_SEARCH";

/* Modal related */
export const CHANGE_COURSE_MODAL_VISIBILITY = "CHANGE_COURSE_MODAL_VISIBILITY";
export const CHANGE_EXAM_MODAL_VISIBILITY = "CHANGE_EXAM_MODAL_VISIBILITY";

/* Course page related */
export const SET_COURSE_INFO = "SET_COURSE_INFO";
export const UPDATE_EXAMS = "UPDATE_EXAMS";

/* Exam page related */
export const SET_EXAM_QUESTIONS = "SET_EXAM_QUESTIONS";
export const CHANGE_SUB_QUESTION_SOLUTION = "CHANGE_SUB_QUESTION_SOLUTION";
export const CHANGE_EXAM_ID = "CHANGE_EXAM_ID";
