version: "3"

services:
  server:
    image: golang
#    restart: always
    volumes:
      - .:/go/src/examplar
    working_dir: /go/src/examplar
    command: go run main.go
    links:
      - database

  database:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false

      - DB_USER=examplar
      - DB_PASS=password
      - DB_NAME=examplar
    volumes:
      - /srv/docker/postgresql:/var/lib/postgresql
