/* Home page */
export const UPDATE_COURSE_SEARCH = "UPDATE_COURSE_SEARCH";

/* University search box related */
export const UPDATE_UNIVERSITY_SEARCH = "UPDATE_UNIVERSITY_SEARCH";

/* Modal related */
export const UPDATE_COURSE_MODAL_VISIBILITY = "UPDATE_COURSE_MODAL_VISIBILITY";
export const UPDATE_EXAM_MODAL_VISIBILITY = "UPDATE_EXAM_MODAL_VISIBILITY";

/* Course page related */
export const SET_COURSE_INFO = "SET_COURSE_INFO";
export const UPDATE_EXAMS = "UPDATE_EXAMS";

/* Exam page related */
export const SET_EXAM_QUESTIONS = "SET_EXAM_QUESTIONS";
export const UPDATE_SOLUTIONS = "UPDATE_SOLUTIONS";
export const UPDATE_EXAM_ID = "UPDATE_EXAM_ID";
export const UPDATE_USER_SOLUTION = "UPDATE_USER_SOLUTION";
export const UPDATE_SUB_QUESTION_ID = "UPDATE_SUB_QUESTION_ID";
export const RESET_EXAM_PAGE = "RESET_EXAM_PAGE";
export const UPDATE_PREVIEW_SWITCH_STATE = "UPDATE_PREVIEW_SWITCH_STATE";
